apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-07-17T01:46:11Z"
  labels:
    app: terraria
  name: my-service
  namespace: jon-terraria-ns
  resourceVersion: "243091"
  selfLink: /api/v1/namespaces/jon-terraria-ns/services/my-service
  uid: a79ce402-a834-11e9-b951-0a11b313b133
spec:
  clusterIP: 10.245.236.155
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31821
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: terraria
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 159.203.159.8

